export const defaultDataBase = {
  lists: [
    {
      name: "Today",
      colorId: 8,
      tasks: [],
      id: 1,
    },
    {
      name: "This Week",
      colorId: 3,
      tasks: [],
      id: 2,
    },
    {
      name: "This Month",
      colorId: 5,
      tasks: [],
      id: 3,
    },
    {
      name: "Camping",
      colorId: 6,
      tasks: [],
      id: 4,
    },
    {
      name: "Shopping",
      colorId: 7,
      tasks: [],
      id: 5,
    },
    {
      name: "Other",
      colorId: 4,
      tasks: [],
      id: 6,
    },
  ],
  tasks: [
    {
      listId: 1,
      text: "New page",
      completed: true,
      id: 1,
    },
    {
      listId: 1,
      text: "Send the new page to John",
      completed: true,
      id: 2,
    },
    {
      listId: 1,
      text: "Check lists",
      completed: false,
      id: 3,
    },
    {
      listId: 1,
      text: "Finalize budget",
      completed: true,
      id: 4,
    },
    {
      listId: 1,
      text: "Refine messaging",
      completed: false,
      id: 5,
    },
    {
      listId: 2,
      text: "Analyze campaign performance",
      completed: false,
      id: 6,
    },
    {
      listId: 2,
      text: "Conduct user research",
      completed: true,
      id: 7,
    },
    {
      listId: 2,
      text: "Hire new copywriter",
      completed: false,
      id: 8,
    },
    {
      listId: 2,
      text: "Launch iOS app",
      completed: false,
      id: 9,
    },
    {
      listId: 2,
      text: "Redesign homepage",
      completed: true,
      id: 10,
    },
    {
      listId: 3,
      text: "Engage Jupiter Express for outer solar system travel",
      completed: false,
      id: 11,
    },
    {
      listId: 3,
      text: "Create 90 day plans for all departments in the Mars Office",
      completed: false,
      id: 12,
    },
    {
      listId: 3,
      text: "Engage Saturn's Rings Resort as a preferred provider",
      completed: true,
      id: 13,
    },
    {
      listId: 3,
      text: "Enable Speedy SpaceCraft as the preferred",
      completed: true,
      id: 14,
    },
    {
      listId: 4,
      text: "Tent",
      completed: false,
      id: 15,
    },
    {
      listId: 4,
      text: "Sleeping bag",
      completed: true,
      id: 16,
    },
    {
      listId: 4,
      text: "bug spray",
      completed: false,
      id: 17,
    },
    {
      listId: 4,
      text: "flashlight",
      completed: false,
      id: 18,
    },
    {
      listId: 4,
      text: "fishing pole",
      completed: true,
      id: 19,
    },
    {
      listId: 5,
      text: "Hamburger",
      completed: false,
      id: 20,
    },
    {
      listId: 5,
      text: "Milk",
      completed: true,
      id: 21,
    },
    {
      listId: 5,
      text: "Cheese",
      completed: true,
      id: 22,
    },
    {
      listId: 5,
      text: "Butter",
      completed: true,
      id: 23,
    },
    {
      listId: 5,
      text: "Bread",
      completed: true,
      id: 24,
    },
    {
      listId: 6,
      text: "Camping",
      completed: true,
      id: 25,
    },
    {
      listId: 6,
      text: "New laptop",
      completed: false,
      id: 26,
    },
    {
      listId: 6,
      text: "Bills",
      completed: true,
      id: 27,
    },
  ],
  colors: [
    {
      id: 1,
      color: "#C9D1D3",
      name: "grey",
    },
    {
      id: 2,
      color: "#42B883",
      name: "green",
    },
    {
      id: 3,
      color: "#64C4ED",
      name: "blue",
    },
    {
      id: 4,
      color: "#FFBBCC",
      name: "pink",
    },
    {
      id: 5,
      color: "#B6E6BD",
      name: "lime",
    },
    {
      id: 6,
      color: "#C355F5",
      name: "purple",
    },
    {
      id: 7,
      color: "#110133",
      name: "black",
    },
    {
      id: 8,
      color: "#FF6464",
      name: "red",
    },
  ],
};
